package planalimenticio;

import database.Connect;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Equipo1
 */
class Interfaz extends javax.swing.JFrame {
	
    private double IMC;
    private double PGC;
    private double MCM;
    private double TMB;
    private double CxD;
    private double PxD;

    /**
     * Constructor
     */
    Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlresultados.hide();
        btnSiguiente.setVisible(false);
        rbtnmasculino.setSelected(true);
        txtcadera.enable(false);
		
        this.altura_txt.setText("170");
        this.peso_txt.setText("65");
        this.cintura_txt.setText("80");
        this.cuello_txt.setText("40");
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngsexo = new javax.swing.ButtonGroup();
        lbltitulo = new javax.swing.JLabel();
        pnldatos = new javax.swing.JPanel();
        lblaltura = new javax.swing.JLabel();
        altura_txt = new javax.swing.JTextField();
        lblpeso = new javax.swing.JLabel();
        cintura_txt = new javax.swing.JTextField();
        lblcintura = new javax.swing.JLabel();
        peso_txt = new javax.swing.JTextField();
        lblcuello = new javax.swing.JLabel();
        cuello_txt = new javax.swing.JTextField();
        lblcadera = new javax.swing.JLabel();
        txtcadera = new javax.swing.JTextField();
        lblsexo = new javax.swing.JLabel();
        rbtnmasculino = new javax.swing.JRadioButton();
        rbtnfemenino = new javax.swing.JRadioButton();
        lblnivelact = new javax.swing.JLabel();
        nivel_act_cmb = new javax.swing.JComboBox<>();
        btncalcular = new javax.swing.JButton();
        pnlresultados = new javax.swing.JPanel();
        lblcxd = new javax.swing.JLabel();
        lblpxd = new javax.swing.JLabel();
        lblcalorias = new javax.swing.JLabel();
        lblproteinas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("Plan Alimenticio");

        lblaltura.setText("Altura (CM):");

        altura_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altura_txtKeyTyped(evt);
            }
        });

        lblpeso.setText("Peso(KG):");

        cintura_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cintura_txtKeyTyped(evt);
            }
        });

        lblcintura.setText("Cintura(CM):");

        peso_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                peso_txtKeyTyped(evt);
            }
        });

        lblcuello.setText("Cuello(CM):");

        cuello_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuello_txtKeyTyped(evt);
            }
        });

        lblcadera.setText("Cadera(CM):");

        txtcadera.setText("Hombres opcional");
        txtcadera.setToolTipText("");
        txtcadera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcaderaMouseClicked(evt);
            }
        });
        txtcadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaderaKeyTyped(evt);
            }
        });

        lblsexo.setText("Sexo:");

        btngsexo.add(rbtnmasculino);
        rbtnmasculino.setText("Masculino");
        rbtnmasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnmasculinoMouseClicked(evt);
            }
        });

        btngsexo.add(rbtnfemenino);
        rbtnfemenino.setText("Femenino");
        rbtnfemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnfemeninoMouseClicked(evt);
            }
        });

        lblnivelact.setText("Nievel de actividad:");

        nivel_act_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentario", "Ligero", "Moderado", "Intensa" }));
        nivel_act_cmb.setSelectedItem("");
        nivel_act_cmb.setToolTipText("");

        javax.swing.GroupLayout pnldatosLayout = new javax.swing.GroupLayout(pnldatos);
        pnldatos.setLayout(pnldatosLayout);
        pnldatosLayout.setHorizontalGroup(
            pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldatosLayout.createSequentialGroup()
                        .addComponent(lblnivelact)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldatosLayout.createSequentialGroup()
                            .addComponent(nivel_act_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addGroup(pnldatosLayout.createSequentialGroup()
                            .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblaltura)
                                .addComponent(lblpeso)
                                .addComponent(lblcintura)
                                .addComponent(lblcuello)
                                .addComponent(lblcadera)
                                .addComponent(lblsexo))
                            .addGap(18, 18, 18)
                            .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnldatosLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnfemenino)
                                        .addComponent(rbtnmasculino)))
                                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(peso_txt)
                                    .addComponent(altura_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cintura_txt)
                                    .addComponent(cuello_txt)
                                    .addComponent(txtcadera)))
                            .addContainerGap()))))
        );
        pnldatosLayout.setVerticalGroup(
            pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaltura)
                    .addComponent(altura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpeso)
                    .addComponent(peso_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cintura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcintura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcuello)
                    .addComponent(cuello_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcadera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsexo)
                    .addComponent(rbtnmasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnfemenino)
                .addGap(18, 18, 18)
                .addComponent(lblnivelact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nivel_act_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lblcxd.setText("Calorias por dia:");

        lblpxd.setText("Proteinas por dia:");

        jLabel1.setText("Resultados");

        jLabel2.setText("IMC:");

        javax.swing.GroupLayout pnlresultadosLayout = new javax.swing.GroupLayout(pnlresultados);
        pnlresultados.setLayout(pnlresultadosLayout);
        pnlresultadosLayout.setHorizontalGroup(
            pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlresultadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblproteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(pnlresultadosLayout.createSequentialGroup()
                .addGroup(pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblpxd))
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcxd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlresultadosLayout.setVerticalGroup(
            pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlresultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcxd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpxd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblproteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setName("btnSiguiente"); // NOI18N
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lbltitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btncalcular)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbltitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pnlresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncalcular)
                    .addComponent(btnSiguiente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void altura_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altura_txtKeyTyped
        if(typedNumber(evt)) evt.consume();
    }//GEN-LAST:event_altura_txtKeyTyped

    private void peso_txtKeyTyped(java.awt.event.KeyEvent evt) {                                  
        if(typedNumber(evt)) evt.consume();
    }                                 

    private void cintura_txtKeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(typedNumber(evt)) evt.consume();
    }                                    

    private void cuello_txtKeyTyped(java.awt.event.KeyEvent evt) {                                    
        if(typedNumber(evt)) evt.consume();
    }                                   

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
		
        double altura,peso,cintura,cuello,cadera = 0,nivelact=0;
        String sexo="", snivelact="";

        if(altura_txt.getText().isEmpty()) 
            JOptionPane.showMessageDialog(null, "Campo altura vacio");
        else {  
            altura = Double.parseDouble(altura_txt.getText());
            if(peso_txt.getText().isEmpty()) 
                JOptionPane.showMessageDialog(null, "Campo peso vacio");
            else {
                peso = Double.parseDouble(peso_txt.getText());
                if(cintura_txt.getText().isEmpty()) 
                    JOptionPane.showMessageDialog(null, "Campo cintura vacio");
                else {
                    cintura = Double.parseDouble(cintura_txt.getText());
                    if(cuello_txt.getText().isEmpty()) 
                        JOptionPane.showMessageDialog(null, 
                                "Campo cuello vacio");
                    else {
                        cuello = Double.parseDouble(cuello_txt.getText());
                        if(rbtnmasculino.isSelected()) 
                            sexo = "Masculino";
                        else {
                            sexo = "Femenino";
                            if(txtcadera.getText().isEmpty()) 
                                JOptionPane.showMessageDialog(null, 
                                        "Campo cadera vacio");
                            else  cadera = Double.parseDouble(txtcadera.getText());
                        }
                        snivelact = (String)nivel_act_cmb.getSelectedItem();
                        switch(snivelact) {
                            case "Sedentario":
                                nivelact=1.2;
                                break;
                            case "Ligero":
                                nivelact=1.375;
                                break;
                            case "Moderado":
                                nivelact=1.55;
                                break;
                            case "Intensa":
                                nivelact=1.725;
                                break;
                        }
						
                        IMC = Math.rint(Operaciones.IMC(peso,altura) * 100) / 100;
                        PGC = Operaciones.PGC(cintura, cuello, altura, cadera, sexo);
                        MCM = Operaciones.MCM(peso, PGC);
                        TMB = Operaciones.TMB(MCM);
                        CxD = Math.round(Operaciones.CxD(TMB, nivelact));
                        PxD = Math.rint(Operaciones.PxD(peso) * 100) / 100;
                        
                        System.out.println("Sexo: "+ sexo);
                        System.out.println("Nivel de act.: "+ nivelact + "  ("+ 
                                snivelact +")");
                        System.out.println("PGC: "+ PGC);
                        System.out.println("IMC: "+ IMC);
						
                        lblIMC.setText(String.valueOf(IMC));
                        lblproteinas.setText(String.valueOf(PxD));
                        lblcalorias.setText(String.valueOf(CxD));
                        pnlresultados.show();
                        btnSiguiente.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_btncalcularActionPerformed

    private void txtcaderaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcaderaMouseClicked
      txtcadera.setText("");
    }//GEN-LAST:event_txtcaderaMouseClicked

    private void txtcaderaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaderaKeyTyped
        if(typedNumber(evt)) evt.consume();
    }//GEN-LAST:event_txtcaderaKeyTyped

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        Desayuno desayuno = new Desayuno(this.CxD);
        desayuno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void rbtnmasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnmasculinoMouseClicked
       txtcadera.enable(false);
    }//GEN-LAST:event_rbtnmasculinoMouseClicked

    private void rbtnfemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnfemeninoMouseClicked
       txtcadera.enable(true);
    }//GEN-LAST:event_rbtnfemeninoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura_txt;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btncalcular;
    private javax.swing.ButtonGroup btngsexo;
    private javax.swing.JTextField cintura_txt;
    private javax.swing.JTextField cuello_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblaltura;
    private javax.swing.JLabel lblcadera;
    private javax.swing.JLabel lblcalorias;
    private javax.swing.JLabel lblcintura;
    private javax.swing.JLabel lblcuello;
    private javax.swing.JLabel lblcxd;
    private javax.swing.JLabel lblnivelact;
    private javax.swing.JLabel lblpeso;
    private javax.swing.JLabel lblproteinas;
    private javax.swing.JLabel lblpxd;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JComboBox<String> nivel_act_cmb;
    private javax.swing.JTextField peso_txt;
    private javax.swing.JPanel pnldatos;
    private javax.swing.JPanel pnlresultados;
    private javax.swing.JRadioButton rbtnfemenino;
    private javax.swing.JRadioButton rbtnmasculino;
    private javax.swing.JTextField txtcadera;
    // End of variables declaration//GEN-END:variables
	
	private boolean typedNumber(java.awt.event.KeyEvent evt) {
		return evt.getKeyChar()<'0' || evt.getKeyChar()>'9';
	}
	
	// ELIMINARA ESTA FUNCION
	private void testConnectionDB() {
		try {
			Connect connect = new Connect();
			
			if(connect.isClosed()) {
				System.out.println("No se pudo conectar a la base de datos :'(");
			} else {
				System.out.println("Recuperando algunos registros:");
				ResultSet results = connect.Select("SELECT Tipo, Nombre, Calorias FROM Alimentos WHERE Id_Alimentos<10");
				if(results != null) {
					while(results.next()) {
						System.out.println(results.getString("Tipo") + "\t" + results.getString("Nombre") + "\t" + results.getString("Calorias"));
					}
				}
			}
		} catch (SQLException ex) {
			System.out.println("Error: " + ex.getMessage());
		}
	}
}
